name: datting_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  camera: ^0.10.6
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^17.1.2
  get: ^4.6.6
  path_provider: ^2.1.3
  socket_io_client: ^2.0.3+1
  http: ^1.2.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.5
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/video/video_3.mp4
    - assets/loveBirds/
    - assets/emoji/
    - assets/sticker/
    - assets/riv/
    - assets/Banner/
    - assets/gpay.json
    - assets/audio/call.mp3